// Mocks generated by Mockito 5.4.2 from annotations
// in my_heroes/test/heroes_module/domain/usecase/get_hero_usecase.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_heroes/heroes_module/data/remote_datasource/entity/dto.dart'
    as _i2;

import 'get_hero_usecase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStatusResponse_0<T> extends _i1.SmartFake
    implements _i2.StatusResponse<T> {
  _FakeStatusResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HeroServiceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeroServiceTest extends _i1.Mock implements _i3.HeroServiceTest {
  MockHeroServiceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StatusResponse<dynamic>> fetchHeroes({int? length = 0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchHeroes,
          [],
          {#length: length},
        ),
        returnValue: _i4.Future<_i2.StatusResponse<dynamic>>.value(
            _FakeStatusResponse_0<dynamic>(
          this,
          Invocation.method(
            #fetchHeroes,
            [],
            {#length: length},
          ),
        )),
      ) as _i4.Future<_i2.StatusResponse<dynamic>>);
}
